// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wanted-Linx/linx-backend/api/ent/predicate"
	"github.com/Wanted-Linx/linx-backend/api/ent/projectclub"
)

// ProjectClubDelete is the builder for deleting a ProjectClub entity.
type ProjectClubDelete struct {
	config
	hooks    []Hook
	mutation *ProjectClubMutation
}

// Where appends a list predicates to the ProjectClubDelete builder.
func (pcd *ProjectClubDelete) Where(ps ...predicate.ProjectClub) *ProjectClubDelete {
	pcd.mutation.Where(ps...)
	return pcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pcd *ProjectClubDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pcd.hooks) == 0 {
		affected, err = pcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProjectClubMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcd.mutation = mutation
			affected, err = pcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pcd.hooks) - 1; i >= 0; i-- {
			if pcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcd *ProjectClubDelete) ExecX(ctx context.Context) int {
	n, err := pcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pcd *ProjectClubDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: projectclub.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: projectclub.FieldID,
			},
		},
	}
	if ps := pcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pcd.driver, _spec)
}

// ProjectClubDeleteOne is the builder for deleting a single ProjectClub entity.
type ProjectClubDeleteOne struct {
	pcd *ProjectClubDelete
}

// Exec executes the deletion query.
func (pcdo *ProjectClubDeleteOne) Exec(ctx context.Context) error {
	n, err := pcdo.pcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectclub.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pcdo *ProjectClubDeleteOne) ExecX(ctx context.Context) {
	pcdo.pcd.ExecX(ctx)
}
