// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wanted-Linx/linx-backend/api/ent/predicate"
	"github.com/Wanted-Linx/linx-backend/api/ent/projectlogparticipant"
)

// ProjectLogParticipantDelete is the builder for deleting a ProjectLogParticipant entity.
type ProjectLogParticipantDelete struct {
	config
	hooks    []Hook
	mutation *ProjectLogParticipantMutation
}

// Where appends a list predicates to the ProjectLogParticipantDelete builder.
func (plpd *ProjectLogParticipantDelete) Where(ps ...predicate.ProjectLogParticipant) *ProjectLogParticipantDelete {
	plpd.mutation.Where(ps...)
	return plpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (plpd *ProjectLogParticipantDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(plpd.hooks) == 0 {
		affected, err = plpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProjectLogParticipantMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			plpd.mutation = mutation
			affected, err = plpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(plpd.hooks) - 1; i >= 0; i-- {
			if plpd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = plpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, plpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (plpd *ProjectLogParticipantDelete) ExecX(ctx context.Context) int {
	n, err := plpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (plpd *ProjectLogParticipantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: projectlogparticipant.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: projectlogparticipant.FieldID,
			},
		},
	}
	if ps := plpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, plpd.driver, _spec)
}

// ProjectLogParticipantDeleteOne is the builder for deleting a single ProjectLogParticipant entity.
type ProjectLogParticipantDeleteOne struct {
	plpd *ProjectLogParticipantDelete
}

// Exec executes the deletion query.
func (plpdo *ProjectLogParticipantDeleteOne) Exec(ctx context.Context) error {
	n, err := plpdo.plpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectlogparticipant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (plpdo *ProjectLogParticipantDeleteOne) ExecX(ctx context.Context) {
	plpdo.plpd.ExecX(ctx)
}
