// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wanted-Linx/linx-backend/api/ent/predicate"
	"github.com/Wanted-Linx/linx-backend/api/ent/projectlog"
)

// ProjectLogDelete is the builder for deleting a ProjectLog entity.
type ProjectLogDelete struct {
	config
	hooks    []Hook
	mutation *ProjectLogMutation
}

// Where appends a list predicates to the ProjectLogDelete builder.
func (pld *ProjectLogDelete) Where(ps ...predicate.ProjectLog) *ProjectLogDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *ProjectLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pld.hooks) == 0 {
		affected, err = pld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProjectLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pld.mutation = mutation
			affected, err = pld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pld.hooks) - 1; i >= 0; i-- {
			if pld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *ProjectLogDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *ProjectLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: projectlog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: projectlog.FieldID,
			},
		},
	}
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
}

// ProjectLogDeleteOne is the builder for deleting a single ProjectLog entity.
type ProjectLogDeleteOne struct {
	pld *ProjectLogDelete
}

// Exec executes the deletion query.
func (pldo *ProjectLogDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *ProjectLogDeleteOne) ExecX(ctx context.Context) {
	pldo.pld.ExecX(ctx)
}
