// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
