// Code generated by entc, DO NOT EDIT.

package projectclub

const (
	// Label holds the string label denoting the projectclub type in the database.
	Label = "project_club"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClubID holds the string denoting the club_id field in the database.
	FieldClubID = "club_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// EdgeClub holds the string denoting the club edge name in mutations.
	EdgeClub = "club"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeProjectLog holds the string denoting the project_log edge name in mutations.
	EdgeProjectLog = "project_log"
	// Table holds the table name of the projectclub in the database.
	Table = "project_clubs"
	// ClubTable is the table that holds the club relation/edge.
	ClubTable = "project_clubs"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
	// ClubColumn is the table column denoting the club relation/edge.
	ClubColumn = "club_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_clubs"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// ProjectLogTable is the table that holds the project_log relation/edge.
	ProjectLogTable = "project_logs"
	// ProjectLogInverseTable is the table name for the ProjectLog entity.
	// It exists in this package in order to avoid circular dependency with the "projectlog" package.
	ProjectLogInverseTable = "project_logs"
	// ProjectLogColumn is the table column denoting the project_log relation/edge.
	ProjectLogColumn = "project_club_project_log"
)

// Columns holds all SQL columns for projectclub fields.
var Columns = []string{
	FieldID,
	FieldClubID,
	FieldProjectID,
	FieldStartDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
